# config.toml
[app]
port=":8080"
mode = "release"

[mysql]
host = "localhost"
port = 3306
username = "root"
password = "password"
database = "mydb"

[redis]
host = "localhost"
port = 6379
password = "password"
db = 0
